[[redirects]]
  from = "/api/*"
  to = "https://api.steampowered.com/"
  status = 200
  force = true

[build]
  command = "npm run  build && cd functions/node-fetch && npm install"
  functions = "functions"
  publish = "dist"