[[redirects]]
  from = "https://dawn-of-cry.netlify.app/api"
  to = "https://api.steampowered.com/"
  status = 200
  force = true

  [[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
