[[redirects]]
  from = "/api/*"
  to = "https://api.steampowered.com/"
  status = 200
  force = true

[build]
  command = "yarn build && cd functions/dota && yarn"
  functions = "functions"
  publish = "dist"